#!/usr/bin/env python3
"""Append, validate, or inspect a simulation event ledger."""

from __future__ import annotations

import argparse
import fcntl
import hashlib
import json
import os
from pathlib import Path

from jsonschema import Draft202012Validator, FormatChecker


ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "schemas" / "autoresearch-event.schema.json"
TERMINAL_STATES = {
    "complete_measured",
    "complete_invalid",
    "failed_transient",
    "failed_deterministic",
    "missing_measurement",
    "needs_investigation",
    "stale_provenance",
}
CONTINUE_DECISIONS = {"adjust_range", "continue_search", "promote"}
EXIT_RETRY = 10
EXIT_STOP = 20


def canonical(value: object) -> bytes:
    return json.dumps(
        value, allow_nan=False, separators=(",", ":"), sort_keys=True
    ).encode()


def event_hash(event: dict) -> str:
    payload = {key: value for key, value in event.items() if key != "event_hash"}
    return hashlib.sha256(canonical(payload)).hexdigest()


def schema_errors(event: object) -> list[str]:
    schema = json.loads(SCHEMA.read_text())
    validator = Draft202012Validator(schema, format_checker=FormatChecker())
    return [error.message for error in validator.iter_errors(event)]


def read_events(path: Path):
    with path.open(encoding="utf-8") as stream:
        for line_number, line in enumerate(stream, 1):
            if not line.strip():
                continue
            try:
                yield line_number, json.loads(
                    line,
                    parse_constant=lambda value: (_ for _ in ()).throw(
                        ValueError(f"invalid JSON constant {value}")
                    ),
                )
            except (json.JSONDecodeError, ValueError) as error:
                raise ValueError(f"{path}:{line_number}: {error}") from error


def sequence_errors(events) -> list[str]:
    errors = []
    previous_hash = None
    case_state = {}
    for line_number, event in events:
        prefix = f"line {line_number}"
        for error in schema_errors(event):
            errors.append(f"{prefix}: {error}")
        if event.get("previous_event_hash") != previous_hash:
            errors.append(f"{prefix}: broken previous_event_hash")
        if event.get("event_hash") != event_hash(event):
            errors.append(f"{prefix}: broken event_hash")
        previous_hash = event.get("event_hash")

        case_key = event.get("case_key")
        attempt = event.get("attempt")
        retry_count = event.get("retry_count")
        state = event.get("state")
        if not isinstance(attempt, int) or not isinstance(retry_count, int):
            continue
        if retry_count != attempt - 1:
            errors.append(f"{prefix}: retry_count must equal attempt - 1")
        prior = case_state.get(case_key)
        if prior is None:
            if attempt != 1:
                errors.append(f"{prefix}: first case event must use attempt 1")
        elif attempt == prior["attempt"]:
            if prior["terminal"]:
                errors.append(f"{prefix}: event follows a terminal state in the same attempt")
            if state == prior["state"]:
                errors.append(f"{prefix}: duplicate state in the same attempt")
        elif attempt == prior["attempt"] + 1:
            if not prior["terminal"] or not prior["retryable"]:
                errors.append(f"{prefix}: new attempt was not authorized by a retryable terminal event")
        else:
            errors.append(f"{prefix}: attempts must be consecutive")
        case_state[case_key] = {
            "attempt": attempt,
            "state": state,
            "terminal": state in TERMINAL_STATES,
            "retryable": event.get("retryable") is True,
        }
    return errors


def validate_log(path: Path):
    events = list(read_events(path))
    return sequence_errors(events), events


def append_event(path: Path, payload: dict) -> dict:
    if "previous_event_hash" in payload or "event_hash" in payload:
        raise ValueError("hash fields are generated by the ledger")
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a+", encoding="utf-8") as stream:
        fcntl.flock(stream, fcntl.LOCK_EX)
        stream.seek(0)
        existing = list(read_events(path))
        prior_hash = existing[-1][1]["event_hash"] if existing else None
        record = dict(payload, previous_event_hash=prior_hash, event_hash="0" * 64)
        record["event_hash"] = event_hash(record)
        errors = sequence_errors([*existing, (len(existing) + 1, record)])
        if errors:
            raise ValueError("; ".join(errors))
        stream.seek(0, os.SEEK_END)
        stream.write(canonical(record).decode() + "\n")
        stream.flush()
        os.fsync(stream.fileno())
        fcntl.flock(stream, fcntl.LOCK_UN)
    return record


def action(event: dict) -> dict:
    if event["retryable"]:
        run_action = "retry"
    elif event["state"] in {"planned", "running"}:
        run_action = "wait"
    elif event["decision"] in CONTINUE_DECISIONS:
        run_action = "continue"
    else:
        run_action = "stop"
    return {
        "status": "valid",
        "case_key": event["case_key"],
        "attempt": event["attempt"],
        "state": event["state"],
        "retryable": event["retryable"],
        "should_stop": run_action == "stop",
        "run_action": run_action,
        "decision": event["decision"],
        "next_action": event["next_action"],
        "stop_reason": event["stop_reason"],
    }


def parser():
    result = argparse.ArgumentParser()
    subparsers = result.add_subparsers(dest="command", required=True)
    append = subparsers.add_parser("append")
    append.add_argument("log", type=Path)
    source = append.add_mutually_exclusive_group(required=True)
    source.add_argument("--event", help="event payload as JSON")
    source.add_argument("--event-file", type=Path)
    validate = subparsers.add_parser("validate")
    validate.add_argument("log", type=Path)
    inspect = subparsers.add_parser("inspect")
    inspect.add_argument("log", type=Path)
    inspect.add_argument("--case-key")
    inspect.add_argument("--exit-code", action="store_true")
    return result


def main() -> int:
    args = parser().parse_args()
    try:
        if args.command == "append":
            text = args.event_file.read_text() if args.event_file else args.event
            record = append_event(args.log, json.loads(text))
            print(json.dumps(action(record), separators=(",", ":")))
            return 0
        errors, events = validate_log(args.log)
        if errors:
            print(json.dumps({
                "status": "invalid",
                "retryable": False,
                "should_stop": True,
                "errors": errors,
                "next_action": "Repair the first invalid event before resuming.",
            }, separators=(",", ":")))
            return 1
        if args.command == "validate":
            print(json.dumps({"status": "valid", "events": len(events)}, separators=(",", ":")))
            return 0
        selected = [item for _, item in events if args.case_key in {None, item["case_key"]}]
        if not selected:
            raise ValueError("no matching event")
        result = action(selected[-1])
        print(json.dumps(result, separators=(",", ":")))
        if args.exit_code and result["run_action"] == "retry":
            return EXIT_RETRY
        if args.exit_code and result["run_action"] == "stop":
            return EXIT_STOP
        return 0
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(json.dumps({
            "status": "error",
            "retryable": False,
            "should_stop": True,
            "error": str(error),
            "next_action": "Repair the ledger or event payload before resuming.",
        }, separators=(",", ":")))
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
